name: Check pull request
run-name: ${{ github.actor }} is checking his pull request

on:
  pull_request:
    branches: 
      - main

jobs:
  Preparation-and-Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        uses: ./.github/composite-actions/install-deps

      - name: Run linters
        run: |
          npm run lint

      - name: Check that project builds successfully
        run: |
          npm run build
